spring:
  application:
    name: storkly
  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: false
  mail:
    properties:
      "[mail.smtp.auth]": "true"
      "[mail.smtp.starttls.enable]": "true"

server:
  port: 8080
  shutdown: graceful

management:
  tracing:
    export:
      enabled: false

springdoc:
  api-docs:
    path: /api/docs
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true

storkly:
  mail:
    from: noreply@storkly.app
